src/models/Navigation.php
<?php namespace Rubber\Admin;

use Illuminate\Database\Eloquent\SoftDeletingTrait;

class Navigation extends HierarchyBaseModel
{
	use SoftDeletingTrait;

	protected $table = 'rubber_navigations';

	public $fillable = [
		'name',
		'description',
		'icon',
		'route_name',
		'route_to'
	];

	public static $rules = [
		'name'       => 'required',
		'parent_id'  => 'required|exists:rubber_navigations,id',
		'route_name' => 'required_without:route_to',
		'route_to'   => 'required_without:route_name'
	];

	public static $messages = [
		'name'       => [
			'required' => 'Please specify a menu name'
		],
		'parent_id'  => [
			'required' => 'Please choose a parent menu, or select the root item if the menu is on the top level',
			'exists'   => 'The selected parent menu with id [:value] does not exists'
		],
		'route_name' => 'Please specify a route name for this menu, or specify a url below',
		'route_to'   => 'Please specify a url if a route name is not specify'
	];

	// 'parent_id' column name
	protected $parentColumn = 'parent_id';

	// 'lft' column name
	protected $leftColumn = 'lft';

	// 'rgt' column name
	protected $rightColumn = 'rght';

	// 'depth' column name
	protected $depthColumn = 'depth';

	// guard attributes from mass-assignment
	protected $guarded = [
		'id',
		'parent_id',
		'lft',
		'rght',
		'depth'
	];


	public function depth($repeator)
	{
		return str_repeat($repeator . ' ', $this->attributes['depth']);
	}


	public function parent()
	{
		return $this->belongsTo('Rubber\Admin\Navigation', 'parent_id');
	}


	public function getNameWithIconAttribute()
	{
		$name = $this->attributes['name'];
		$name = $this->getIconTagAttribute() . ' ' . $name;

		return $name;
	}


	public function getIconTagAttribute()
	{
		if ( ! empty( $this->attributes['icon'] )) {
			return \Html::icon($this->attributes['icon']);
		}

		return false;
	}


	public function getIntendedRouteAttribute()
	{
		return empty( $this->attributes['route_to'] )
			? $this->attributes['route_name']
			: $this->attributes['route_to'];
	}

}

src/controllers/NavigationController.php
<?php namespace Rubber\Admin;

use BaseController;
use Baum\MoveNotPossibleException;
use View;
use Redirect;
use Input;
use Validator;
use Route;
use MessageBag;
use Request;

class NavigationController extends BaseController
{

	protected $_root;


	public function __construct()
	{
		$this->_root = Navigation::root();
		if (empty( $this->_root )) {
			// Create default ROOT.
			$this->_root = Navigation::create([
				'name'        => 'Top Level',
				'description' => 'This is the root node',
				'route_name'  => '',
				'route_to'    => '/',
				'icon'        => ''
			]);
		}
	}


	public function missingMethod($parameters = [])
	{
		$message = new MessageBag;
		$message->add('errors', 'The navigation does not exists.');

		return Redirect::route('admin.navigation.list')
		               ->withErrors($message);
	}


	protected function getRoot()
	{
		return $this->_root;
	}


	protected function getTree()
	{
		return $this->_root->getDescendantsAndSelf()
		                   ->all();
	}


	/**
	 * Determine if a route has any variables
	 *
	 * @param $route
	 *
	 * @return bool
	 */

	protected function hasVariables($route)
	{
		$uri = $route->getUri();

		return preg_match('/{+(.*?)}/', $uri);
	}


	// Return an array of "GET" routes, without any parameter requirements.
	protected function getRoutes()
	{
		$definedRoutes = Route::getRoutes()
		                      ->getRoutes();
		$routes        = [];
		foreach ($definedRoutes as $route) {
			if ( ! in_array('GET', $route->getMethods())) {
				continue;
			}
			$name = $route->getName();
			if (empty( $name )) {
				continue;
			}
			if ($this->hasVariables($route)) {
				continue;
			}
			$routes[$name] = $name;
		}

		return $routes;
	}


	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$tree = $this->getTree();

		return View::make('rubber::navigations.index')
		           ->with(compact('tree'));
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		if (Request::ajax()) {
			return View::make('rubber::navigations.partials.quickMenu');
		}
		$tree   = $this->getRoot();
		$tree   = $tree->getNestedList('name');
		$routes = $this->getRoutes();

		return View::make('rubber::navigations.create')
		           ->with(compact('tree', 'routes'));
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$rules      = Navigation::$rules;
		$message    = Navigation::$messages;
		$validation = Validator::make(Input::all(), $rules, $message);
		if ($validation->passes()) {
			$navigation = Navigation::create(Input::all());
			try {
				$parent = Navigation::findOrFail(Input::get('parent_id'));
				$navigation->makeChildOf($parent);
			} catch (MoveNotPossibleException $e) {
				if (Request::ajax()) {
					return Redirect::route('admin.navigation.create')
					               ->withErrors($validation)
					               ->withInput();
				}
				$message = new \Illuminate\Support\MessageBag;
				$message->add('error', $e->getMessage());

				return Redirect::route('admin.navigation.create')
				               ->withInput()
				               ->with('errors', $message);
			}
			$navigation->makeChildOf($parent);
			if (Request::ajax()) {
				return 'saved';
			}

			return Redirect::route('admin.navigation.list')
			               ->with('message', 'A new navigation menu has been added.');

		} else {
			return Redirect::route('admin.navigation.create')
			               ->withErrors($validation)
			               ->withInput();
		}
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show(Navigation $navigation)
	{
		$descendants = $navigation->getDescendants();

		return View::make('rubber::navigations.show')
		           ->with(compact('navigation', 'descendants'));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param Navigation $navigation
	 *
	 * @return Response
	 * @internal param int $id
	 *
	 */
	public function edit(Navigation $navigation)
	{
		$tree   = $this->getRoot();
		$tree   = $tree->getNestedList('name');
		$routes = $this->getRoutes();

		return View::make('rubber::navigations.edit')
		           ->with(compact('navigation', 'tree', 'routes'));
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param Navigation $navigation
	 *
	 * @return Response
	 *
	 */
	public function update(Navigation $navigation)
	{
		$rules   = Navigation::$rules;
		$message = Navigation::$messages;
		if ($navigation->isRoot()) {
			unset( $rules['parent_id'] );
		}
		$validation = Validator::make(Input::all(), $rules, $message);
		if ($validation->passes()) {
			$navigation->fill(Input::all());
			$navigation->save();
			// move the node of the parent id changes, except the root node which cannot be moved
			if ( ! $navigation->isRoot()) {
				try {
					$parent = Navigation::findOrFail(Input::get('parent_id'));
					$navigation->makeChildOf($parent);
				} catch (MoveNotPossibleException $e) {
					$message = new \Illuminate\Support\MessageBag;
					$message->add('error', $e->getMessage());

					return Redirect::route('admin.navigation.edit', $navigation->id)
					               ->with('errors', $message);
				}
			}

			return Redirect::route('admin.navigation.list')
			               ->with('message', 'The menu ' . $navigation->name . ' has been updated.');

		} else {
			return Redirect::route('admin.navigation.edit', $navigation->id)
			               ->withErrors($validation)
			               ->withInput();
		}
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param Navigation $navigation
	 *
	 * @return Response redirect
	 */
	public function destroy(Navigation $navigation)
	{
		if (is_null($navigation->parent_id)) {
			return Redirect::route('admin.navigation.list')
			               ->with('message',
				               'The navigation menu <strong>' . $navigation->name . '</strong> is the root menu. The root menu cannot be deleted.');
		}
		$navigation->delete();

		return Redirect::route('admin.navigation.list')
		               ->with('message',
			               'The navigation menu <strong>' . $navigation->name . '</strong> has been removed.');
	}


	public function reorder()
	{
		$navigations = Navigation::all()
		                         ->toHierarchy();

		return View::make('rubber::navigations.sort')
		           ->with(compact('navigations'));
	}


	public function applyOrder()
	{
		return;
	}

}

src/views/foundation/navigations/create.blade.php
@extends('rubber::layouts.form')

	@section('content_header')
		Navigation Builder : Create Menu
	@stop

	@section('form')
		{{ Form::open(array( 'route' => 'admin.navigation.store', 'method' => 'post')) }}
			@include('rubber::navigations.partials.form')
		{{ Form::close() }}
	@stop

src/views/foundation/navigations/edit.blade.php
@extends('rubber::layouts.form')

	@section('content_header')
		Navigation Builder :
		@if($navigation->is_divider)
			Edit Separator : {{{ $navigation->name }}}
		@else
			Edit menu : {{{ $navigation->name }}}
		@endif

	@stop

	@section('form')
		{{ Form::model($navigation, array( 'route' => array('admin.navigation.update', $navigation->id),  'method' => 'patch' )) }}
			@include('rubber::navigations.partials.form')
		{{ Form::close() }}
	@stop

src/views/foundation/navigations/index.blade.php
@extends('rubber::layouts.table')

	@section('content_header')
		Navigation Builder
	@stop
	@section('table')
		@include('rubber::navigations.partials.table', compact('tree'))
	@stop

src/views/foundation/navigations/show.blade.php
@extends('rubber::layouts.detail')

	@section('content_header')
		<h2>{{ $navigation->icon_tag }} {{ $navigation->name }}</h2>
	@stop
	@section('detail')
		<div class="row">
			<div class="large-3 columns small-12 columns">
				{{ $navigation->name_with_icon }}
			</div>
			<div class="large-9 columns small-12 columns">
				@include('rubber::navigations.partials.table', ['tree' => 'descendants'])
			</div>
		</div>
	@stop

src/views/foundation/navigations/sort.blade.php
@extends('rubber::layouts.detail')

	@section('content_header')
		<h2>Navigation Builder: Sort Position</h2>
	@stop
	@section('detail')
		<div class="row">
			<div  class="large-12 columns">
				<div id="tree">
					<ol>
						@foreach($navigations as $nav)
							@include('rubber::navigations.partials.branch', ['leave' => $nav])
						@endforeach
					</ol>
				</div>
			</div>
		</div>
	@stop

	@section('bottomScript')
		@parent

		<script>
		$(function(){
			var list = $("#tree");
			var callbacks ={};
			callbacks.post = "{{ route('admin.navigation.reorder.apply') }}";
			list.sortable({
				items: 'li',
				containment: '#tree',
				handle: '.leave',
				helper: 'clone',
				cursor: 'move',
				placeholder: 'sortable-placeholder',
				forcePlaceholderSize: true,
				dropOnEmpty: true,
				start: function(event, ui){
					list.find('ol').each(function(i, sublist){
						if($(sublist).find('li').length == 0){
							$(sublist).append("<li class='dummy'>drop here</li>");
						}

					});
				},
				stop: function(event, ui){
					 $(".dummy").remove();
				},
				update: function( event, ui ) {
					list.sortable("disable");
					$.post(
						callbacks.post,
						{
							 ids: list.sortable("toArray"),
						},
						function(response){
							list.sortable("enable");
						}
					);
				}
			}).disableSelection();;
		})
		</script>
	@stop