src/models/User.php
<?php namespace Rubber\Admin;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;
use Gravatar;
use Sentry;
use Html;
use Str;
use Image;

class User extends \Cartalyst\Sentry\Users\Eloquent\User
{

	public static $rules = [
		'email'      => 'required|unique:users|email',
		'password'   => 'min:5|confirmed',
		'first_name' => 'required',
		'avatar'     => 'image|max:300'
	];

	public static $messages = [
		'email.required'      => 'Please enter a valid email adress.',
		'email.email'         => 'Please enter a valid email adress.',
		'email.unique'        => 'The email has already been used by another user.',
		'password.min'        => 'The password must be at least :min characters',
		'password.confirmed'  => 'The password did not matched.',
		'first_name.required' => 'Please enter the first name of this user',

	];

	protected $fillable = [
		'first_name',
		'last_name',
		'email',
		'avatar',
		'password',
		'activated',
		'permissions'
	];

	protected $path = [
		'avatar' => 'packages/rubber/admin/avatars/'
	];

	protected static $observer = 'Rubber\Admin\Observer\UserObserver';


	protected static function boot()
	{
		parent::boot();
		self::observe(new self::$observer);
	}


	/**
	 * Return the path to a folder specify inside the model.
	 *
	 * @param $folder
	 *
	 * @return   [type]         [description]
	 * @throws Exception\PathInvalidException
	 * @throws Exception\PathNotFoundException
	 *
	 * @todo     Code copy from Rubber\Admin\BaseModel since we cannot extends the base model here. Maybe upgrade it when
	 *         possible with Traits ?
	 */
	public function getPath($folder)
	{
		if (empty( $folder )) {
			throw new Exception\PathInvalidException('The path ' . $folder . ' is not defined in the ' . get_class($this));
		}
		if (empty( $this->path[$folder] )) {
			throw new Exception\PathNotFoundException('The path ' . $folder . ' is not defined in the ' . get_class($this));
		}

		return $this->path[$folder];
	}


	public function getDates()
	{
		return [
			'created_at',
			'updated_at',
			'last_login'
		];
	}


	public function access()
	{
		return $this->hasMany('Rubber\Admin\UserAccess', 'user_id');
	}


	public function history()
	{
		return $this->hasMany('Rubber\Admin\UserHistory', 'user_id');
	}


	public function notifications()
	{
		return $this->hasMany('Rubber\Admin\User\Notification', 'user_id');
	}


	public function outgoing()
	{
		return $this->hasMany('Rubber\Admin\User\Notification', 'sender_id');
	}


	public function getFullNameAttribute()
	{
		$name = $this->attributes['first_name'] . ' ' . $this->attributes['last_name'];
		$name = trim($name);

		return $name;
	}


	public function getFullNameOrEmailAttribute()
	{
		$name = $this->getFullNameAttribute();
		if (empty( $name )) {
			return $this->attributes['email'];
		}

		return $name;
	}


	public function getFullNameAndEmailAttribute()
	{
		return $this->getFullNameAttribute() . ' <' . $this->attributes['email'] . '>';
	}


	public function getActivatedTextAttribute()
	{
		return $this->attributes['activated']
			? 'Activated'
			: 'Pending';
	}


	// An allias accessor method for getAvatarImagePathAttribute().
	public function getAvatarImageSrcAttribute()
	{
		if (empty( $this->attributes['avatar'] )) {
			return Gravatar::src($this->attributes['email']);
		} else {
			return asset($this->getAvatarSrcAttribute());
		}
	}


	public function getAvatarImagePathAttribute()
	{
		if (empty( $this->attributes['avatar'] )) {
			return Gravatar::src($this->attributes['email']);
		} else {
			return asset($this->getAvatarSrcAttribute());
		}
	}


	public function getMyselfAttribute()
	{
		return $this->attributes['id'] === \Sentry::getUser()->id;
	}


	public function notify($message, $mail = false)
	{

	}


	public function getAvatarSrcAttribute()
	{
		return $this->getPath('avatar') . $this->attributes['avatar'];
	}


	public function setAvatarAttribute(UploadedFile $src = null)
	{
		if ($src instanceOf UploadedFile) {
			$dest     = $this->getPath('avatar');
			$filename = sprintf('user-%s-%s.%s', $this->attributes['id'], time(), $src->getClientOriginalExtension());
			$src->move($dest, $filename);
			$this->removeAvatar();
			$this->attributes['avatar'] = $filename;

			$image = Image::make($this->getAvatarSrcAttribute())
			              ->resize(300, null, function ($constraint) {
				              $constraint->aspectRatio();
			              })
			              ->save();
		}

		return;
	}


	// Remove the avatar photo tf the user, set it to null.
	// BIG NOTE: the save() must be called manually to update the value.
	public function removeAvatar()
	{
		if ( ! empty( $this->attributes['avatar'] )) {
			$image = $this->getAvatarSrcAttribute();
			if (File::exists($image)) {
				File::delete($image);
			}
			$this->attributes['avatar'] = null;
		}

		return;
	}


	public function hasPhoto()
	{
		return ! empty( $this->attributes['avatar'] );
	}


	public function getAccessLogUrlAttribute()
	{
		return route('admin.user.show.access', $this->attributes['id']);
	}


	public function getHistoryLogUrlAttribute()
	{
		return route('admin.user.show.history', $this->attributes['id']);
	}


	public function getProfileUrlAtribute()
	{
		return route('admin.user.show', $this->attributes['id']);
	}


	public function getPrivilegeUrlAttribute()
	{
		return route('admin.user.privilege', $this->attributes['id']);
	}


	/**
	 * Copied utiiity code from basemodel since we cannot extends from the basemodel
	 */
	public function scopeApplyFilter($query, $filters = [])
	{
		if ( ! empty( $filters )) {
			if ( ! empty( $filters['name'] )) {
				$query->where(function ($query) use ($filters) {
					return $query->whereLike('first_name', $filters['name'])
					             ->orWhereLike('last_name', $filters['name']);
				});
			}
			if ( ! empty( $filters['email'] )) {
				$query->whereLike('email', $filters['email']);
			}
			if ( ! empty( $filters['group'] )) {
				$groups_id = $filters['group'];
				$query->whereHas('groups', function ($query) use ($groups_id) {
					return $query->whereIn('id', $groups_id);
				});
			}
		}

		return $query;
	}


	protected function label($type = null, $content = null, $attributes = [])
	{
		if (empty( $type )) {
			$type = 'secondary circular';
		}
		if (is_array($attributes)) {
			$attributes = Html::attributes($attributes);
		}
		$pattern = '<span class="label %s" %s>%s</span>';

		return sprintf($pattern, $type, $attributes, $content);
	}


	public function labelError($attributes = null)
	{
		$icon = Html::icon('fa-trash fa-lg error');

		return $this->label('alert circular', $icon, $attributes);
	}


	public function labelSuccess($attributes = null)
	{
		$icon = Html::icon('fa-check fa-lg');

		return $this->label('success circular', $icon, $attributes);
	}


	protected function getLikePattern($wrapping = 'both')
	{
		switch (strtolower($wrapping)) {
			case 'left':
				$pattern = "%%%s";
				break;
			case 'right':
				$pattern = "%s%%";
				break;
			case 'both':
				$pattern = "%%%s%%";
				break;
			default:
				throw new InvalidArgumentException('The wrapping value for LIKE condition must be either `left`, `right` or `both`');
		}

		return $pattern;
	}


	public function scopeWhereLike($query, $field, $value, $wrapping = 'both')
	{
		$pattern = self::getLikePattern($wrapping);

		return $query->where($field, 'LIKE', sprintf($pattern, $value));
	}


	public function scopeOrWhereLike($query, $field, $value, $wrapping = 'both')
	{
		$pattern = self::getLikePattern($wrapping);

		return $query->orWhere($field, 'LIKE', sprintf($pattern, $value));
	}


	protected function tooltip($text)
	{
		$tooltip = [
			'title'        => $text,
			'data-tooltip' => '',
			'class'        => 'has-tip tip-top',
		];

		return $tooltip;
	}


	public function getStatusLabelAttribute()
	{

		$throttle = Sentry::findThrottlerByUserId($this->id);
		if ($throttle->isBanned()) {
			$tooltip = $this->tooltip('user banned on ' . $throttle->banned_at);
			$icon    = Html::icon('fa fa-times fa-lg');

			return $this->label('alert circular', $icon, $tooltip);
		}
		if ($throttle->isSuspended()) {
			$tooltip = $this->tooltip('user suspended at ' . $throttle->banned_at);
			$icon    = Html::icon('fa fa-times fa-lg');

			return $this->label('secondary circular', $icon, $tooltip);
		}
		if ($this->isActivated()) {
			$tooltip = $this->tooltip('activated');
			$icon    = Html::icon('fa fa-check fa-lg');

			return $this->label('success circular', $icon, $tooltip);
		} else {
			$tooltip = $this->tooltip('not activated');
			$icon    = Html::icon('fa fa-clock-o fa-lg');

			return $this->label('secondary circular', $icon, $tooltip);
		}
	}

}

src/views/foundation/users/access.blade.php
@extends('rubber::layouts.detail')

	@section('content_header')
	<h2>User Information : {{{ $user->full_name_or_email }}}</h2>
	@stop

	@section('detail')

		<div class="row">

			@include('rubber::users.partials.info')

			<div class="large-9 columns">
				<header><h3>Access Log</h3></header>
				@include('rubber::users.partials.accessLogs', compact('access'))
				{{ $access->links() }}
			</div>
		</div>
	@stop

src/views/foundation/users/assignRoles.blade.php
@extends('rubber::layouts.table')

	@section('content_header')
		Manage Roles of: {{ $user->full_name }}
	@stop
	@section('table')
		<table>
			<thead>
				<tr>
					<th>Assign</th>
					<th>Name</th>
					<th>Permissions</th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<td></td>
					<td></td>
					<td></td>
				</tr>
			</tfoot>
			<tbody>
			@unless($groups)
				<tr>
					<td colspan="3">No groups available</td>
				</tr>
			@else
				@foreach($groups as $group)
				<tr>
					<td></td>
					<td>{{ $group->name }}</td>
					<td>
						@foreach($group->permissions as $k=>$perm)
							{{$k }} : {{ $perm }}<br>
						@endforeach
					</td>
				</tr>
				@endforeach
			@endunless
			</tbody>
		</table>

	@stop

src/views/foundation/users/create.blade.php
@extends('rubber::layouts.base')

	@section('content')

		<header>
			<h2><i class="fa fa-lg fa-user"></i> Create New User</h2>
		</header>

		{{ Form::open(array( 'route' => 'admin.user.store', 'method' => 'post' )) }}
		<div class="row">
			<div class="large-8 columns">
				<div class="panel">
					<header><h3>Account Information</h3></header>
					@include('rubber::users.partials.form')
					{{ Html::submit(' Create Account
					') }}
					<a href="{{ route('admin.user.list') }}" class="small button secondary"><i class="fa fa-times fa-lg"></i> Cancel</a>
				</div>
			</div>
			<div class="large-4 columns">
				<div class="panel">
					<header><h3>Optional Settting</h3></header>

					<div class="row">
						<div class="large-6 columns">
							<label>
								{{ Tinker::checkbox('activate', 1) }}
								Activate on create
							</label>

						</div>
					</div>

					<div class="row">
						<div class="large-12 columns">
							<label for="">Privileges</label>
							{{ Form::select('group_ids[]', $groups, null, array( 'class' => 'chosen', 'multiple' => true)) }}
						</div>
					</div>

				</div>

			</div>
		</div>
		{{ Form::close() }}

	@stop

src/views/foundation/users/edit.blade.php
@extends('rubber::layouts.form')

	@section('content_header')
		User: {{{ $user->full_name_or_email}}} - edit
	@stop
	@section('form')
		<div class="row">
			@include('rubber::users.partials.info')
			<div class="large-9 columns">

				<div class="section-container auto" data-section data-options="deep_linking: true">

					<section class="active">
						<p class="title" data-section-title><a href="#information">Account Information</a></p>
						<div class="content" data-section-content data-slug="information">
							<header><h3><i class="fa fa-user fa-lg"></i> Account Information</h3></header>

							<div class="row">
								<div class="large-10 columns">
								@if($user->id == Sentry::getID())
									{{ Form::model($user, array(
										'route' => array('admin.self.update'),
										'method' => 'patch',
										'files' => true
										))
									}}
									@else
									{{ Form::model($user, array(
										'route' => array('admin.user.update', $user->id),
										'method' => 'patch',
										'files' => true
										))
									}}
									@endif

									@include('rubber::users.partials.form')
									@include('rubber::users.partials.password')

									<div class="row">
										<div class="large-12 columns">
											{{ HTML::submit( 'Save') }}
										</div>
									</div>

									{{ Form::close() }}
								</div>

								<div class="large-2 columns">
									@unless(empty($user))
										<label>Current Photo</label>
										<img src="{{ $user->avatar_image_path }}" class="th round">
											@if($user->hasPhoto())
										{{ Html::delete( ' remove photo', route('admin.user.photo.delete', $user->id) )}}
										@endif
									@else

									@endunless
								</div>
							</div>

						</div>
					</section>

<!--
					<section>
						<p class="title" data-section-title><a href="#password">Change Account Password</a></p>
						<div class="content" data-section-content data-slug="password">
							<header><h3><i class="fa fa-key fa-lg"></i> Change Account Password</h3></header>
							{{ Form::open(array(
								'route' => array('admin.user.password.update', $user->id),
								'method' => 'patch'))
							}}

							<div class="row">
								<div class="large-10 columns">
									@include('rubber::users.partials.authenticate')
								</div>
							</div>


							<div class="row">
								<div class="large-12 columns">
									{{ HTML::submit( 'Change Password') }}
								</div>
							</div>

							{{ Form::close() }}
						</div>
					</section>
 -->
				</div>
			</div>
		</div>

	@stop

src/views/foundation/users/history.blade.php
@extends('rubber::layouts.detail')

	@section('content_header')
	<h2>User Information : {{{ $user->full_name_or_email }}}</h2>
	@stop

	@section('detail')

		<div class="row">

			@include('rubber::users.partials.info')

			<div class="large-9 columns panel">
				<header><h3>Activity History</h3></header>
				@include('rubber::users.partials.historyLog', compact('history'))
				{{ $history->links() }}
			</div>
		</div>
	@stop

src/views/foundation/users/index.blade.php
@extends('rubber::layouts.base')

	@section('content_header')

	@stop

	@section('content')

		<div class="row">
			<div class="large-9 columns">
				<header>
					<h2>{{ Html::icon('fa-users') }} Users Account
						@if(!empty($group))
						<small>{{{ $group->name }}}</small>
						@endif
					</h2>
				</header>
				@include('rubber::users.partials.table', compact('user'))
			</div>
			<div class="large-3 columns">
				<header>
					<h2><i class="fa fa-search fa-lg"></i> Search Users</h2>
				</header>
				@include('rubber::users.partials.filters')
			</div>
		</div>


	@stop

src/views/foundation/users/permission.blade.php
		<fieldset>
			<legend>Privileges</legend>
			<div class="row">
				{{ Form::label('Group') }}
				{{ Form::select('group', $groups) }}
			</div>
			<div class="row">
				{{ Form::label('Additional Permission') }}
				{{ Form::text('permissions') }}
			</div>
			{{ Form::submit() }}
		</fieldset>

src/views/foundation/users/privilege.blade.php
@extends('rubber::layouts.form')

	@section('content_header')
		User: {{{ $user->full_name_or_email }}} - Privilege
	@stop
	@section('form')
		<div class="row">
			@include('rubber::users.partials.info')
			<div class="large-9 columns">
				{{ Form::open(array('url' => $user->privilege_url, 'method' => 'patch') ) }}
				<table>
				<thead>
					<tr>
						<th width="80"></th>
						<th width="200">Group</th>
						<th>Description</th>
					</tr>
				</thead>
				<tbody>
					@foreach($groups as $group)
					<tr>
						<td class="text-center">
							<label for="group_{{ $group->id }}">{{ Form::checkbox('group_ids[]', $group->id, $user->inGroup($group), array( 'id' => 'group_'.$group->id)) }}</label>
						</td>
						<td><label for="group_{{ $group->id }}">{{{ $group->name }}}</label></td>
						<td>{{{ $group->description }}}</td>
					</tr>
					@endforeach
				</tbody>
				<tfoot>
					<tr>
						<td></td>
						<td colspan="2">{{ Html::submit('Grant Access') }}</td>
					</tr>
				</tfoot>
				</table>

				{{ Form::close() }}
			</div>
		</div>

	@stop

src/views/foundation/users/show.blade.php
@extends('rubber::layouts.base')
	@section('content')
		<header>
			<h2>{{ Html::icon('fa-users') }} User : {{{ $user->full_name_or_email }}}</h2>
		</header>
		<div class="row">

			@include('rubber::users.partials.info')

			<div class="large-9 columns">
				<div class="section-container auto" data-section data-options="deep_linking: true">

					<section>
						<p class="title" data-section-title><a href="#group-permissions">Group Permissions</a></p>
						<div class="content" data-section-content data-slug="group-permissions">
							<header><h3>Group Permissions</h3></header>
							@include('rubber::users.partials.permissions', ['permissions' => $user->getMergedPermissions(), 'bibles' => $bibles])
						</div>
					</section>

				</div>
			</div>
		</div>
	@stop